AllCops:
 Rails:
   Enabled: true
 Exclude:
   - db/*/*
   - db/schema.rb
   - config/*/*
   - config/*.rb
   - script/**
   - bin/*
   - Rakefile
   - spec/spec_helper.rb
   - spec/rails_helper.rb
   - Gemfile
   - Gemfile.lock
   - config.ru

Metrics/ClassLength:
 CountComments: false
 Max: 200

Metrics/ModuleLength:
 CountComments: false
 Max: 200

Metrics/MethodLength:
 CountComments: false
 Max: 20

Style/AccessorMethodName:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false